#!/bin/sh

if ! id -u "proof" >/dev/null 2>&1; then
        adduser --system --group --home /home/proof --shell /bin/bash proof
fi

if ! grep -q /etc/sudoers.d/proof -e '%proof ALL=NOPASSWD: /sbin/shutdown' >/dev/null 2>&1; then
        echo "%proof ALL=NOPASSWD: /sbin/shutdown" >> /etc/sudoers.d/proof
fi

if ! grep -q /etc/sudoers.d/proof -e '%proof ALL=NOPASSWD: /usr/bin/apt-get' >/dev/null 2>&1; then
        echo "%proof ALL=NOPASSWD: /usr/bin/apt-get" >> /etc/sudoers.d/proof
fi
