#!/bin/sh

RESTARTER_PATH=##APP_RESTARTER_PATH##

if [ -f "$RESTARTER_PATH"/down_should_be_removed ]; then
    rm -f "$RESTARTER_PATH"/down || true
fi
rm -f "$RESTARTER_PATH"/down_should_be_removed || true

if ! id -u "proof" >/dev/null 2>&1; then
        adduser --system --group --home /home/proof --shell /bin/bash proof
fi

if ! grep -q /etc/sudoers.d/proof -e '%proof ALL=NOPASSWD: /sbin/shutdown' >/dev/null 2>&1; then
        echo "%proof ALL=NOPASSWD: /sbin/shutdown" >> /etc/sudoers.d/proof
fi

if ! grep -q /etc/sudoers.d/proof -e '%proof ALL=(root) NOPASSWD: /sbin/ifup' >/dev/null 2>&1; then
        echo "%proof ALL=(root) NOPASSWD: /sbin/ifup" >> /etc/sudoers.d/proof
fi

if ! grep -q /etc/sudoers.d/proof -e '%proof ALL=(root) NOPASSWD: /sbin/ifdown' >/dev/null 2>&1; then
        echo "%proof ALL=(root) NOPASSWD: /sbin/ifdown" >> /etc/sudoers.d/proof
fi

if ! grep -q /etc/sudoers.d/proof -e '%proof ALL=(root) NOPASSWD: /usr/sbin/openvpn' >/dev/null 2>&1; then
        echo "%proof ALL=(root) NOPASSWD: /usr/sbin/openvpn" >> /etc/sudoers.d/proof
fi

if ! grep -q /etc/sudoers.d/proof -e '%proof ALL=(root) NOPASSWD: /usr/bin/pkill openvpn' >/dev/null 2>&1; then
        echo "%proof ALL=(root) NOPASSWD: /usr/bin/pkill openvpn" >> /etc/sudoers.d/proof
fi

if ! grep -q /etc/sudoers.d/proof -e '%proof ALL=(root) NOPASSWD: /bin/cp /tmp/interfaces_tmp /etc/network/interfaces' >/dev/null 2>&1; then
        echo "%proof ALL=(root) NOPASSWD: /bin/cp /tmp/interfaces_tmp /etc/network/interfaces" >> /etc/sudoers.d/proof
fi

if ! grep -q /etc/sudoers.d/proof -e '%proof ALL=(root) NOPASSWD: /bin/cp /tmp/opensoft-external-customers-vpn.conf /etc/openvpn/opensoft-external-customers-vpn.conf' >/dev/null 2>&1; then
        echo "%proof ALL=(root) NOPASSWD: /bin/cp /tmp/opensoft-external-customers-vpn.conf /etc/openvpn/opensoft-external-customers-vpn.conf" >> /etc/sudoers.d/proof
fi

if ! grep -q /etc/sudoers.d/proof -e '%proof ALL=(root) NOPASSWD: /bin/touch /etc/openvpn/opensoft-external-customers-vpn.conf' >/dev/null 2>&1; then
        echo "%proof ALL=(root) NOPASSWD: /bin/touch /etc/openvpn/opensoft-external-customers-vpn.conf" >> /etc/sudoers.d/proof
fi

